CREATE TABLE IF NOT EXISTS tb_phones (
	id BIGINT generated by default as identity,
	number VARCHAR(20) NOT NULL,
	type VARCHAR(20) CHECK (TYPE IN ('WHATSAPP','CELULAR','RESIDENCIAL','COMERCIAL')),

	PRIMARY KEY (id)
);